#!/bin/sh

export logtime=1466394847
export path_log=${path_log}10
export camparl=$path_aws/campar/roi270_540/cpl.yml
export camparr=$path_aws/campar/roi270_540/cpr.yml
export campars=$path_aws/campar/roi270_540/stcp.yml

