#!/bin/sh

export logtime=1464500936
export path_log=($path_log)2
export camparl=$path_aws/campar/roi0_960/cpl.yml
export camparr=$path_aws/campar/roi0_960/cpr.yml
export campars=$path_aws/campar/roi0_960/stcp.yml
