#!/bin/bash

rec=n
sim=n
rep=n

for arg in $*
do
    if [[ $arg =~ ^[A-Za-z0-9_]*=[A-Za-z0-9_]*$ ]]; then
	param=(${arg//=/ })
	case ${param[0]} in
	    "sim") sim=${param[1]};;
	    "rec") rec=${param[1]};;
	    "rep") rep=${param[1]};;
	esac
    fi    
done

nohup aws > /dev/null &
sleep 3 
cd hsys
./start.aws rec=$rec sim=$sim rep=$rep
cd ..
