#!/bin/sh

env=`uname`
if [ $env = "Linux" ]; then
    export path_aws=/mnt/ssd1/aws
    export path_data=/mnt/ssd1/aws
else
    user=`whoami`
    export path_aws=c:/cygwin64/home/$user/aws
    export path_data=d:/aws
fi
