#!/bin/sh

swidth=1936
sheight=1216
width=1920
height=1080
Ttrig=333000
StreamBytesPersecond=100000000
PacketSize=8228
nfrmbuf=5
Gain=0
GainAuto=Continuous
GainAutoMax=20
GainAutoMin=0
ExposureAuto=Continuous #Off, Once, Continuous
ExposureAutoMax=10000
ExposureAutoMin=100
ExposureTimeAbs=
fmt_out=BGR8
fmt=Bayer8
sz_frmbuf=64
addr=172.18.2.8
free=y
bitrate=10000000
fps=30
