#!/bin/sh

. ./config

if [ $env = "Linux" ]; then
    width=1280
    height=720
else
    width=1920
    height=1080
fi

joystick=0

path_fshader=$path_aws/GLSL/sample.fs
path_vshader=$path_aws/GLSL/sample.vs
path_fnttex=$path_aws/res/gothic40.png
path_fnttexinf=$path_aws/res/gothic40.fontsettings

nf=225
flah=220
hfah=210
slah=200
dsah=152
stp=127
dsas=102
slas=53
hfas=43
flas=33

has=255
s20=213
s10=173
mds=133
p10=89
p20=45
hap=0
