#!/bin/sh

env=`uname`
if [ $env = "Linux" ]; then
    export path_aws=/mnt/ssd1/aws
    export path_data=/mnt/ssd1/aws
else
    export path_aws=c:/cygwin64/home/yhmtm/aws
    export path_data=c:/cygwin64/home/yhmtm/aws
fi
