#!/bin/sh

. ./config

if [ $env = "Linux" ]; then
    width=1280
    height=720
else
    width=1920
    height=1080
fi

joystick=0

path_fshader=$path_aws/GLSL/sample.fs
path_vshader=$path_aws/GLSL/sample.vs
path_fnttex=$path_aws/res/gothic40.png
path_fnttexinf=$path_aws/res/gothic40.fontsettings

dsas=105
