#!/bin/sh

export logtime=1464501783
export path_log=${path_log}3
export camparl=$path_aws/campar/roi0_960/cpl.yml
export camparr=$path_aws/campar/roi0_960/cpr.yml
export campars=$path_aws/campar/roi0_960/stcp.yml
