#!/bin/sh

export logtime=1466296429
export path_log=${path_log}7
export camparl=$path_aws/campar/roi0_960/cpl.yml
export camparr=$path_aws/campar/roi0_960/cpr.yml
export campars=$path_aws/campar/roi0_960/stcp.yml
