#!/bin/sh

export log_time=1493276910
export path_log=$path_data/log/jtklog/log012
export campar=$path_data/campar/mako1/par.yml
export roi_x=0
#export roi_y=0
export roi_y=320
export roi_w=1934
#export roi_h=1214
export roi_h=640
export vw_w=1920
export vw_h=640
