#!/bin/sh

ch_state=state
ch_env=env
ch_ctrl_stat=aws1_ctrl_stat
ch_ctrl_ui=aws1_ctrl_ui
ch_ctrl_ap1=aws1_ctrl_ap1
ch_ais_obj=ais_obj

ch_engstate=engstate
ch_wp=wp
ch_ap_inst=ap_inst
ch_img=img

#channel sharing

schh2l="$ch_ctrl_ui $ch_ctrl_ap1"
schl2h="$ch_state $ch_env $ch_ctrl_stat $ch_ais_obj"
