#!/bin/sh


file=test.avi


for arg in $*
do
	case $prev_arg in
	     "file") file=$arg;;	     
	esac
	prev_arg=$arg
done

env=`uname`
cpu=`uname -p`

if [ $env = "Linux" ]; then
    if [ $cpu = "x86_64" ]; then
	echo "filesrc location=$file ! avidemux ! h264parse ! avdec_h264 "	
    else
	echo "filesrc location=$file ! avidemux ! h264parse ! omxh264dec "
    fi
else
    echo "filesrc location=$file ! avidemux ! h264parse ! openh264dec "
fi
