#!/bin/sh


file=test.avi


for arg in $*
do
	case $prev_arg in
	     "file") file=$arg;;	     
	esac
	prev_arg=$arg
done

env=`uname`

if [ $env = "Linux" ]; then
    echo "filesrc location=$file ! avidemux ! h264parse ! omxh264dec "
else
    echo "filesrc location=$file ! avidemux ! h264parse ! openh264dec "
fi
