#!/bin/sh


file=test.avi
width=640
height=480
bitrate=1000000

for arg in $*
do
	case $prev_arg in
	    "file") file=$arg;;
	    "width") width=$arg;;
	    "height") height=$arg;;
	    "bitrate") bitrate=$arg;;
	esac
	prev_arg=$arg
done

echo "video/x-raw,format=I420,width=$width,height=$height,framerate=30/1 ! omxh264enc bitrate=10000000 ! video/x-h264,streamformat=byte-stream ! h264parse ! avimux ! filesink location=$file"
